### ISSUE TITLE
Support fullwidth characters and unicode surrogate pairs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cli-truncate#1]
https://github.com/sindresorhus/cli-truncate/blob/dbc522d6f3c1fd7b287b39521ed73a7c9e98fd66/test.js#L15-L17

Depends on https://github.com/chalk/wrap-ansi/issues/10 and https://github.com/chalk/wrap-ansi/issues/11.
## 

Note to self: Update the readme description when this is fixed.

**Comment by kevva** [comment]
Is this test correct https://github.com/sindresorhus/cli-truncate/blob/dbc522d6f3c1fd7b287b39521ed73a7c9e98fd66/test.js#L16? The surrogate pairs are counted as a single character and not two.

**Comment by sindresorhus** [comment]
> Is this test correct [/test.js@`dbc522d`#L16](https://github.com/sindresorhus/cli-truncate/blob/dbc522d6f3c1fd7b287b39521ed73a7c9e98fd66/test.js#L16)?

No, I don't think it's correct.

**Comment by kevva** [comment]
Nah, me neither. The visual width should only be one character. Will supply a PR with a bump of `slice-ansi` and fixed tests.
