### ISSUE TITLE
Option to choose where to truncate

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cli-truncate#2]
Currently it's truncated at the `end`, but an option could enable truncating at the `start` or in the `middle`.

Not something I need right now, but might be useful in the future.

A good pull request would be much welcome :)

**Comment by portgasd666** [comment]
What would be the expected behavior for truncation at the middle and end ?

**Comment by sindresorhus** [comment]
```js
cliTruncate('unicorn', 5, {position: 'start'});
//=> '…corn'

cliTruncate('unicorn', 5, {position: 'middle'});
//=> 'un…rn'
```

**Comment by portgasd666** [comment]
And if the text spans multiple lines, the part of the text that needs to be visible after truncation would be from the last line right ?

**Comment by portgasd666** [comment]
For position start that is

**Comment by sindresorhus** [comment]
I don't think it makes sense to support multiple lines. It should just treat newline as just another character as it currently does.
