### ISSUE TITLE
Truncates more characters than necessary

### ISSUE THREAD

**Issue by vadimdemedes** [sindresorhus/cli-truncate#23]
Reproduction from the readme:

```js
cliTruncate('unicorn', 4);
//=> 'un…', not 'uni…'
```

Can be reproduced without any changes by pulling a fresh clone of this repository and running `npm test`.

```
❯ npm t

> cli-truncate@3.1.0 test
> xo && ava && tsd


  main

  Difference:

  - 'un…'
  + 'uni…'

  › file://test.js:5:4



  space option

  Difference:

  - 'un …'
  + 'uni …'

  › file://test.js:25:4

  ─

  2 tests failed
```

I reverted https://github.com/sindresorhus/cli-truncate/commit/23b40dc576d53f83a88caa2001ce5341d9f3241c locally and tests are passing now, so it has to be a regression from https://github.com/sindresorhus/cli-truncate/pull/19. cc @codemaster138

**Comment by vadimdemedes** [comment]
Not sure how this didn't fail after merging that pull request and why CI is green now.

**Comment by sindresorhus** [comment]
I'm unable to reproduce this locally, both with 3.1.0 and 4.0.0. My guess would be that it was caused by a sub-dependency which was later fixed.
