### ISSUE TITLE
Ellipsis color is always white

### ISSUE THREAD

**Issue by thiagodp** [sindresorhus/cli-truncate#5]
Hi, 

in `cliTruncate( chalk.gray( someLongFileName ), process.stdout.columns, { position: 'middle' } )` the ellipsis color is white (not gray).

Better having a `color` property in the options, like `{ position: 'middle', color: 'gray' }` ?

Note: tested only on Win10

**Comment by kevva** [comment]
Do this instead:

```js
chalk.gray(cliTruncate(someLongFilename, process.stdout.columns, {positioon: 'middle'}));
```

**Comment by thiagodp** [comment]
Actually, there are more complex cases, such as using more than one color in a line:
```javascript
let hashText = chalk.yellow( ' (' + fileHash.substr( 0, 7 ) + ')' );
let fileText = cliTruncate( chalk.gray( '  ' + file ), ( columns - hashText.length ), { position: 'middle' } );
console.log( fileText + hashText ); // gray + yellow, but the ellipsis is white :)
```
